# Generated by Django 5.0.6 on 2024-08-14 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=240)),
                ('likes', models.IntegerField(default=0)),
                ('quotes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('reply_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_og_comment', to='posts.post')),
            ],
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('quote_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_og_quote', to='posts.post')),
            ],
            bases=('posts.post',),
        ),
    ]
