# Generated by Django 5.0.6 on 2024-08-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster_id',
            new_name='poster',
        ),
    ]
