# Generated by Django 5.0.6 on 2024-08-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_commenter', to='user_profile.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_og_comment', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_liker', to='user_profile.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_og_like', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_og_repost', to='user_profile.userprofile')),
                ('reposter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reposter', to='user_profile.userprofile')),
            ],
        ),
    ]
