# Generated by Django 5.0.6 on 2024-09-04 22:15

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Mars', max_length=20)),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to='media/', validators=[user_profile.models.validate_file_type])),
                ('display_name', models.CharField(default='New User', max_length=12)),
                ('bio', models.CharField(default="I'm new here ! :)", max_length=80)),
                ('background_picture', models.ImageField(blank=True, null=True, upload_to='media/', validators=[user_profile.models.validate_file_type])),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to='user_profile.userprofile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='user_profile.userprofile')),
            ],
        ),
    ]
