# Generated by Django 5.0.6 on 2024-08-17 02:40

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/', validators=[user_profile.models.validate_file_type]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default="I'm new here ! :)", max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='New User', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Mars', max_length=20),
        ),
    ]
